//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDzor.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRUDzor.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this resource?.
        /// </summary>
        internal static string TEXT_ConfirmDelete {
            get {
                return ResourceManager.GetString("TEXT_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard changes?.
        /// </summary>
        internal static string TEXT_ConfirmDiscard {
            get {
                return ResourceManager.GetString("TEXT_ConfirmDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form is not in an edit state and there are no changes to revert..
        /// </summary>
        internal static string TEXT_InvalidCancelState {
            get {
                return ResourceManager.GetString("TEXT_InvalidCancelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form is not in an edit state and there are no changes to save..
        /// </summary>
        internal static string TEXT_InvalidSaveState {
            get {
                return ResourceManager.GetString("TEXT_InvalidSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form contains one or more validation errors..
        /// </summary>
        internal static string TEXT_InvalidSubmit {
            get {
                return ResourceManager.GetString("TEXT_InvalidSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        internal static string TEXT_NotFound {
            get {
                return ResourceManager.GetString("TEXT_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is restricted due to system constraints..
        /// </summary>
        internal static string TEXT_Restricted {
            get {
                return ResourceManager.GetString("TEXT_Restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unauthorized to {0} this..
        /// </summary>
        internal static string TEXT_Unauthorized {
            get {
                return ResourceManager.GetString("TEXT_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string TITLE_ConfirmDelete {
            get {
                return ResourceManager.GetString("TITLE_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Discard.
        /// </summary>
        internal static string TITLE_ConfirmDiscard {
            get {
                return ResourceManager.GetString("TITLE_ConfirmDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Cancel State.
        /// </summary>
        internal static string TITLE_InvalidCancelState {
            get {
                return ResourceManager.GetString("TITLE_InvalidCancelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Save State.
        /// </summary>
        internal static string TITLE_InvalidSaveState {
            get {
                return ResourceManager.GetString("TITLE_InvalidSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Submission.
        /// </summary>
        internal static string TITLE_InvalidSubmit {
            get {
                return ResourceManager.GetString("TITLE_InvalidSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string TITLE_NotFound {
            get {
                return ResourceManager.GetString("TITLE_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Restricted.
        /// </summary>
        internal static string TITLE_Restricted {
            get {
                return ResourceManager.GetString("TITLE_Restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string TITLE_Unauthorized {
            get {
                return ResourceManager.GetString("TITLE_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string TITLE_UnexpectedError {
            get {
                return ResourceManager.GetString("TITLE_UnexpectedError", resourceCulture);
            }
        }
    }
}
